<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp" Version="1.8.2" />
        <PackageReference Include="AngleSharp.Css" Version="1.1.2" />
        <PackageReference Include="Dapper" Version="2.1.89" />
        <PackageReference Include="FluentMigrator.Runner" Version="8.0.1" />
        <PackageReference Include="FluentMigrator.Runner.Postgres" Version="8.0.1" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="Npgsql" Version="10.0.3" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.17.10" />
        <PackageReference Include="Scalar.Net" Version="1.0.3" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
